import { 
  WorklogTask, 
  BacklogTask, 
  MonthlyKpiActuals, 
  TaskCategory, 
  TaskStatus, 
  TaskPriority 
} from "./types";

export const SEED_WORKLOG_TASKS: WorklogTask[] = [
  {
    id: "task-1",
    date: "2026-07-01",
    title: "Post Facebook: 5 Bài Học CRO Từ Đợt Tối Ưu Landing Page Mới",
    category: TaskCategory.CONTENT_MARKETING,
    status: TaskStatus.DONE,
    priority: TaskPriority.HIGH,
    isCaseStudyOrInsight: true,
    kpiImpact: "Social Content",
    notes: "Đã đăng, lượng tương tác tăng 25% so với trung bình",
  },
  {
    id: "task-2",
    date: "2026-07-02",
    title: "Post LinkedIn: Định Vị Sản Phẩm (USP) Cho ICP Nhóm Doanh Nghiệp SaaS",
    category: TaskCategory.CONTENT_MARKETING,
    status: TaskStatus.DONE,
    priority: TaskPriority.MEDIUM,
    isCaseStudyOrInsight: true,
    kpiImpact: "Social Content",
    notes: "Nội dung mang tính chuyên sâu, nhận được nhiều thảo luận chất lượng",
  },
  {
    id: "task-3",
    date: "2026-07-03",
    title: "Xây dựng Product Brief & Launch Plan cho đợt nâng cấp Tính năng tự động hóa v2",
    category: TaskCategory.PRODUCT_MARKETING,
    status: TaskStatus.DONE,
    priority: TaskPriority.HIGH,
    isCaseStudyOrInsight: false,
    kpiImpact: "None",
    notes: "Đã hoàn thành bàn giao cho Dev & Product Team",
  },
  {
    id: "task-4",
    date: "2026-07-04",
    title: "Thiết kế Sales Deck & Pitch Template chuẩn hóa hỗ trợ Sales tư vấn khách B2B",
    category: TaskCategory.SALES_ENABLEMENT,
    status: TaskStatus.DONE,
    priority: TaskPriority.HIGH,
    isCaseStudyOrInsight: false,
    kpiImpact: "Sales Asset / Case Study",
    notes: "Đã gửi đội Sales, hỗ trợ pitch thử nghiệm 2 khách lớn",
  },
  {
    id: "task-5",
    date: "2026-07-05",
    title: "Case Study: Cách CT Alpha Tiết Kiệm 30h/Tuần Với Hệ Thống Tự Động Hóa",
    category: TaskCategory.CUSTOMER_MARKETING,
    status: TaskStatus.DONE,
    priority: TaskPriority.HIGH,
    isCaseStudyOrInsight: true,
    kpiImpact: "Sales Asset / Case Study",
    notes: "Tài liệu dài 4 trang kèm infographic, có đính kèm website",
  },
  {
    id: "task-6",
    date: "2026-07-05",
    title: "Gửi Email Newsletter Campaign: Chia sẻ báo cáo thị trường quý 2",
    category: TaskCategory.CAMPAIGN_MANAGEMENT,
    status: TaskStatus.DONE,
    priority: TaskPriority.MEDIUM,
    isCaseStudyOrInsight: false,
    kpiImpact: "Email Campaign",
    notes: "Tỷ lệ Open Rate đạt 22.4%, CTR đạt 3.8%",
  },
  {
    id: "task-7",
    date: "2026-07-06",
    title: "Post LinkedIn: Bản Tin PLG Case Study - Case Study từ Figma",
    category: TaskCategory.CONTENT_MARKETING,
    status: TaskStatus.DONE,
    priority: TaskPriority.MEDIUM,
    isCaseStudyOrInsight: true,
    kpiImpact: "Social Content",
    notes: "Thu hút 120+ reactions và nhiều lượt shares",
  },
  {
    id: "task-8",
    date: "2026-07-07",
    title: "Gửi Email Campaign: Giới thiệu tính năng tích hợp API tự động",
    category: TaskCategory.CAMPAIGN_MANAGEMENT,
    status: TaskStatus.DONE,
    priority: TaskPriority.HIGH,
    isCaseStudyOrInsight: false,
    kpiImpact: "Email Campaign",
    notes: "Gửi tệp 1,500 active contacts, thu về 12 leads mới",
  },
  {
    id: "task-9",
    date: "2026-07-10",
    title: "Thiết kế & Tối ưu luồng chuyển đổi (CTA) trang chủ chính thức",
    category: TaskCategory.WEBSITE_CRO,
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.HIGH,
    isCaseStudyOrInsight: false,
    kpiImpact: "None",
    notes: "Đang sửa UI/UX, dự kiến deploy tuần 3",
  },
  {
    id: "task-10",
    date: "2026-07-12",
    title: "Post Facebook: 10 lỗi thường gặp khi lập cấu hình Email Automation",
    category: TaskCategory.CONTENT_MARKETING,
    status: TaskStatus.IN_PROGRESS,
    priority: TaskPriority.MEDIUM,
    isCaseStudyOrInsight: false,
    kpiImpact: "Social Content",
    notes: "Đang viết draft, sẽ đăng vào thứ 3 tới",
  },
  {
    id: "task-11",
    date: "2026-07-15",
    title: "Chạy chiến dịch LinkedIn Lead Gen Ads nhắm tệp Product Manager",
    category: TaskCategory.DEMAND_GENERATION,
    status: TaskStatus.TO_DO,
    priority: TaskPriority.HIGH,
    isCaseStudyOrInsight: false,
    kpiImpact: "None",
    notes: "Đang chờ duyệt ngân sách phòng Marketing",
  }
];

export const SEED_BACKLOG_TASKS: BacklogTask[] = [
  {
    id: "backlog-1",
    title: "Nghiên cứu đối thủ cạnh tranh & phân tích bảng giá (Competitor Research 2026)",
    category: TaskCategory.MARKET_RESEARCH,
    priority: TaskPriority.HIGH,
    notes: "Lập bảng so sánh tính năng và mô hình định giá mới của 3 đối thủ lớn nhất",
    createdAt: "2026-07-01",
  },
  {
    id: "backlog-2",
    title: "Xây dựng mẫu Digital Audit phục vụ khách hàng phễu đầu",
    category: TaskCategory.ANALYTICS_REPORTING,
    priority: TaskPriority.MEDIUM,
    notes: "Thiết kế file Google Sheets mẫu để khách tự audit nhanh phễu quảng cáo của họ",
    createdAt: "2026-07-02",
  },
  {
    id: "backlog-3",
    title: "Tối ưu hóa Core Web Vitals của trang Blog",
    category: TaskCategory.WEBSITE_CRO,
    priority: TaskPriority.HIGH,
    notes: "Giảm kích thước file ảnh blog và tối ưu tốc độ tải trang di động",
    createdAt: "2026-07-03",
  },
  {
    id: "backlog-4",
    title: "Thiết kế chuỗi Email Onboarding cho khách dùng thử 14 ngày",
    category: TaskCategory.CAMPAIGN_MANAGEMENT,
    priority: TaskPriority.HIGH,
    notes: "Chuỗi 5 emails tự động kích hoạt dựa trên hành vi sử dụng tính năng của người dùng",
    createdAt: "2026-07-04",
  }
];

export const SEED_KPI_ACTUALS: MonthlyKpiActuals[] = [
  {
    monthKey: "2026-07",
    leadsActual: 8,
    mqlsActual: 5,
    webConvActual: 14,
    emailContactsActual: 24,
  },
  {
    monthKey: "2026-06",
    leadsActual: 11,
    mqlsActual: 6,
    webConvActual: 21,
    emailContactsActual: 32,
  }
];
